src/enforcer.ts, src/model/functionMap.ts, src/model/model.ts
add internal, management and rbac APIs for enforcer
=> internal, management and rbac APIs

README.md
=> Add back linked readme sections

src/model/model.ts
=> Fix buildRoleLinks method

src/enforcer.ts
Reverts casbin/node-casbin#107
=> Revert "improvement: add domain paramter for GetImplicitPermissionsForUser"

README.md
=> add await as getRolesForUser returns Promise.

examples/rbac_with_pattern_model.conf, examples/rbac_with_pattern_policy.csv, src/coreEnforcer.ts, src/rbac/defaultRoleManager.ts, test/model.test.ts
=> feat: add addMatchingFunc to DefaultRoleManager

src/coreEnforcer.ts, src/enforcer.ts, test/model.test.ts
=> fix: avoid miss initialize

src/internalEnforcer.ts, src/managementEnforcer.ts, src/model/model.ts, src/persist/batchAdapter.ts
=> Fix: addPolicies and removePolicies wrappers added with Promise<boolean> returnType.

.github/semantic.yml
Always validate the PR title AND all the commits
=> chore: add semantic.yml

examples/abac_rule_model.conf, examples/abac_rule_policy.csv, src/coreEnforcer.ts, src/util/util.ts, test/enforcer.test.ts, test/util.test.ts
=> fix: Scaling ABAC rules.

src/coreEnforcer.ts, src/effect/defaultEffectorStream.ts, src/effect/effector.ts, src/effect/effectorStream.ts, src/effect/index.ts, src/internalEnforcer.ts, src/managementEnforcer.ts, src/model/assertion.ts, src/model/model.ts
- feat: add BuildIncrementalRoleLinks
- feat: improve effector for improve performance
=> add BuildIncrementalRoleLinks & improve effector for improve performance

package-lock.json, src/coreEnforcer.ts, src/persist/batchFileAdapter.ts, src/persist/index.ts, test/managementAPI.test.ts
I noticed that tests for the batch operations have not been added yet. I have added it. And also like basic ```FileAdapter```, I have added ```BatchFileadapter``` implementation by extending ```FileAdapter``` and implementing ```BatchAdapter```.
=> fix: Add batch tests and BatchFileAdapter implementation.

.releaserc.json, CHANGELOG.md, package-lock.json, package.json, yarn.lock
=> chore: add changelog

src/model/model.ts
Issues: https://github.com/casbin/casbin-editor/issues/14
=> fix: improve tokens separator

package.json
Signed-off-by: Zixuan Liu nodeces@gmail.com
=> chore(release): 5.0.7 [skip ci]

src/frontend.ts, src/index.ts, test/frontend.test.ts
This feature is a support for Casbin.js and it is similar to https://github.com/casbin/casbin/pull/557
=> feat: add casbinJsGetPermissionForUser

src/internalEnforcer.ts
Fix: https://github.com/casbin/node-casbin/issues/177
=> fix: add check if the adapter implements BatchAdapter

src/frontend.ts, test/frontend.test.ts
Signed-off-by: kingiw <kingiw@hotmail.com>
=> fix: update casbinJsGetPermissionForUser for v0.1.0 Casbin.js

src/util/builtinOperators.ts
Fix: https://github.com/casbin/node-casbin/issues/189
=> fix: add cache to generateGFunction

src/coreEnforcer.ts, src/model/model.ts
=> fix: ignore print model

examples/rbac_with_all_pattern_model.conf, examples/rbac_with_all_pattern_policy.csv, examples/rbac_with_domain_pattern_model.conf, examples/rbac_with_domain_pattern_policy.csv, src/rbac/defaultRoleManager.ts, src/util/builtinOperators.ts, test/model.test.ts, test/rbac/defaultRoleManager.test.ts
=> fix: support pattern function in 3rd args of g

tsconfig.cjs.json
Fix: https://github.com/casbin/node-casbin/issues/202
=> feat: changing TypeScript target from ES6 to ES2017

src/util/builtinOperators.ts, test/util.test.ts
fix #214
Signed-off-by: Andreas Bichinger <andreas.bichinger@gmail.com>
=> fix(builtinoperators): fix function keyMatch3

tsconfig.esm.json
=> fix: downgrade target from ESNext to ES2017 for building esm

package.json, test/c.json, yarn.lock
=> ci: update semantic-release

package.json, yarn.lock
=> fix: update expression-eval

src/coreEnforcer.ts, src/syncedEnforcer.ts, src/util/util.ts, test/enforcer.test.ts
Refer to: https://github.com/casbin/node-casbin/pull/226#issuecomment-762933801
Signed-off-by: Xiaotian Lu <xtlu000@gmail.com>
=> feat: enforceSync

README.md
Fix: https://github.com/casbin/node-casbin/issues/231
=> docs: switch CI to GitHub Actions

src/config.ts, test/config/config.test.ts, test/config/testini.ini
=> fix: fix unexpected parser

package.json, src/persist/defaultFilteredAdapter.ts, src/persist/fileAdapter.ts, src/persist/helper.ts, src/persist/stringAdapter.ts, test/persist/helper.test.ts, yarn.lock
=> fix: improve load policy line

.prettierrc, src/coreEnforcer.ts, src/enforcer.ts, src/rbac/defaultRoleManager.ts, src/syncedEnforcer.ts, test/model.test.ts
=> feat: add add_named_matching_func

src/frontend.ts
=> docs: change description of casbinJsGetPermissionForUser

package.json, src/util/builtinOperators.ts, src/util/ip.ts, yarn.lock
ref to discussion at: https://github.com/casbin/node-casbin/issues/257#issuecomment-829001237
node-ip recursively imports os, with this patch node-casbin no longer
includes dependencies on os
=> refactor: Remove the dependency on node-ip

yarn.lock
ref to: https://github.com/casbin/node-casbin/pull/264#discussion_r624634822
=> build: transfer all package link to official

src/util/ip.ts
ref to: https://github.com/casbin/node-casbin/pull/263#issuecomment-830785996
=> chore: add license of node-ip

examples/rbac_g2_model.conf, examples/rbac_g2_policy.csv, src/coreEnforcer.ts, src/model/model.ts, test/enforcer.test.ts
Fix: https://github.com/casbin/node-casbin/issues/261
Fix: https://github.com/casbin/node-casbin/issues/269
=> fix: fix buildRoleLinks

src/coreEnforcer.ts, test/enforcer.test.ts
This PR is based on work of https://github.com/casbin/node-casbin/pull/260, but not break the current API.
I also add corresponding unit tests.
resolve: https://github.com/casbin/node-casbin/issues/256
=> feat: add enforceEx()

src/coreEnforcer.ts, src/enforcer.ts
Fix: https://github.com/casbin/node-casbin/issues/254
=> fix: `getImplicitPermissionsForUser` works with rmMap

src/coreEnforcer.ts
Fix: https://github.com/casbin/node-casbin/issues/278
Signed-off-by: MRGUOKING <420919469@qq.com>
Support for loadIncrementalFilteredPolicy
Signed-off-by: MRGUOKING <420919469@qq.com>
=> fix: Support for loadIncrementalFilteredPolicy

examples/in_operator_model.conf, package.json, src/coreEnforcer.ts, test/frontend.test.ts, test/model.test.ts, yarn.lock
=> feat: add support for `in` operator

tsconfig.json
=> build: adjusting for expression-eval 4

src/enforcer.ts
=> feat: add lazyLoad option at enforcer init method

README.md
=> docs: add missing README

src/internalEnforcer.ts, src/persist/adapter.ts, src/persist/filteredAdapter.ts
=> refactor: reposition filter interface

src/model/functionMap.ts, src/util/builtinOperators.ts, test/util.test.ts
resolve: #301
about: https://github.com/casbin/casbin-editor/issues/47
To address the latter, we should also update the dependency of casbin-editor after this PR got released.
=> feat: add keyGet and keyGet2

examples/in_operator_model.conf, src/coreEnforcer.ts, src/util/util.ts, test/model.test.ts
=> fix: add full supoort for `in` operator

src/coreEnforcer.ts, src/util/util.ts, test/util.test.ts
resolve: #308 
about: https://github.com/casbin/casbin/issues/863
=> fix: add support for legacy array definition method

src/coreEnforcer.ts, test/enforcer.test.ts
=> feat(batchenforce): added batchEnforce

src/enforcer.ts, test/rbacAPI.test.ts
Fix: https://github.com/casbin/node-casbin/issues/340
=> feat: GetImplicitUsersForRole

src/coreEnforcer.ts, src/internalEnforcer.ts, src/persist/index.ts, src/persist/watcherEx.ts
- Need watcherEx to be released to use in node-casbin plugins
- already added in casbin-core
=> feat: add WatcherEx

src/constants.ts, src/effect/defaultEffectorStream.ts, src/enforcer.ts, src/internalEnforcer.ts, src/model/assertion.ts, src/model/model.ts
Fix: https://github.com/casbin/node-casbin/issues/390
sync [casbin#1041](https://github.com/casbin/casbin/pull/1041/files#diff-07fd1bf57992cc1968fc19d2961465f15a8071b8db193a76d001e1f58897550d)
=> feat: add `fieldIndexMap`

.github/workflows/main.yml
Upgraded CI Nodejs version to 14,16,18.
Fix: https://github.com/casbin/node-casbin/issues/408
=> fix: Upgraded CI Nodejs version to v14.16.18.

src/config.ts
=> fix: Multiline Separator Handling

src/coreEnforcer.ts
=> feat: support setNamedRoleManager()

examples/subject_priority_model.conf, examples/subject_priority_model_with_domain.conf, examples/subject_priority_policy.csv, examples/subject_priority_policy_with_domain.csv, src/coreEnforcer.ts, src/effect/defaultEffectorStream.ts, src/model/model.ts, test/enforcer.test.ts
=> feat: support subjectPriority

package.json, src/frontend.ts, test/model.test.ts, yarn.lock
=> fix: remove lodash usage and types

examples/mulitple_policy.csv, src/coreEnforcer.ts, src/enforceContext.ts, src/util/util.ts, test/enforcer.test.ts
Cherry-pick `feat: Multiple sections type` from https://github.com/casbin/casbin-core
=> feat: Multiple sections type

src/config.ts, src/model/model.ts
fix:https://github.com/casbin/casbin-editor/issues/159
=> feat: prevent duplicated sections and invalid operators in config and model

package.json, yarn.lock
fix: https://github.com/casbin/node-casbin/issues/493
=> feat: update to @casbin/expression-eval 5.3.0 to fix short-circuit bug
