src/enforcer.ts

:art: only fileAdapter automatic invoke loadPolicy method, others must invoke manually

change loadPolicy method's invoke

---

src/enforcer.ts
src/persist/adapter.ts
src/persist/defaultFilteredAdapter.ts
src/persist/fileAdapter.ts
src/persist/filteredAdapter.ts
src/util/util.ts
test/enforcer.test.ts
test/model.test.ts
yarn.lock

refactor FileAdapter and Enforcer with async/await

refactor FileAdapter and Enforcer with async/await

---

package.json

to descrease the overall package size considerably.
before
```
"coveralls": "^3.0.2",
"expression-eval": "^1.3.0",
"ip": "^1.1.5",
"lodash": "^4.17.10"
7,294,430 bytes (13.1 MB on disk) for 1,964 items
```
after
```
"expression-eval": "^1.3.0",
"ip": "^1.1.5",
"lodash": "^4.17.10"
2,167,864 bytes (6 MB on disk) for 1,106 items
```
the next step is to use the modularized lodash methods which will bring the package size to around 1MB

set `coveralls` as a dev dependency

---

.travis.yml
examples/rbac_policy.csv
package.json
src/coreEnforcer.ts
test/enforcer.test.ts
test/model.test.ts

Fix: https://github.com/casbin/node-casbin/issues/46

Refactor RoleManager interface and test

---

src/enforcer.ts
src/managementEnforcer.ts
test/enforcer.test.ts
test/managementAPI.test.ts

BREAKING CHANGE: 
There are affected function:
- `getPermissionsForUser()` 
- `hasPermissionForUser()` 
- `getAllSubjects()`
- `getAllNamedSubjects()`
- `getAllObjects()`
- `getAllNamedObjects()`
- `getAllActions()`
- `getAllNamedActions()`
- `getAllRoles()`
- `getAllNamedRoles()`
- `getPolicy()`
- `getFilteredPolicy()`
- `getNamedPolicy()`
- `getFilteredNamedPolicy()`
- `getGroupingPolicy()`
- `getFilteredGroupingPolicy()`
- `getNamedGroupingPolicy()`
- `getFilteredNamedGroupingPolicy()`
- `hasPolicy()`
- `hasNamedPolicy()`
- `hasGroupingPolicy()`
- `hasNamedGroupingPolicy()`
- `addFunction()`

improvement: convert all management_api to async function

---

src/enforcer.ts
test/enforcer.test.ts
test/rbacAPI.test.ts

Fix deleteUser and improve RBAC test coverage

---

src/rbac/defaultRoleManager.ts

In the current version, defaultRoleManager hasRole always returns true if a matchingFunc is provided. This PR fixes it.
Signed-off-by: Alexey Yunoshev <alexey.yunoshev@gmail.com>

fix(rbac): fix defaultRoleManager hasRole method

---

CHANGELOG.md
package.json

* downgrade target from ESNext to ES2017 for building esm ([7dfcf93](https://github.com/casbin/node-casbin/commit/7dfcf93a2eb7a9c9116f55341537a4c81840e3d4))

chore(release): 5.2.3 [skip ci]

---

package.json
yarn.lock

Revert: https://github.com/casbin/node-casbin/pull/222
Fix: https://github.com/casbin/node-casbin/issues/231

fix: downgrade expression-eval back to v2.0.0 to avoid semantic-release failure

---

examples/priority_model_explicit.conf
examples/priority_policy_explicit.csv
examples/priority_policy_explicit_update.csv
src/coreEnforcer.ts
src/internalEnforcer.ts
src/model/model.ts
src/util/util.ts
test/model.test.ts

Fix: https://github.com/casbin/node-casbin/issues/248

feat: add priority_policy_explicit support

---

src/frontend.ts
src/util/util.ts
test/frontend.test.ts

CasbinJsGetPermissionForUser has unexpected side affect. It will change the policy array.

fix: fix CasbinJsGetPermissionForUser()

---

package.json
src/util/builtinOperators.ts
yarn.lock

ref to discussion at https://github.com/casbin/node-casbin/issues/257#issuecomment-829001237
This will remove dependency on `node/util`

fix: transfer from micromatch to picomatch

---

package.json

As for now, `node-casbin` use an outdated `package.json` field `licenses`. And npmjs.com cannot recognize it.
New SPDX format can resolve this problem.

feat: use new license format

---

src/coreEnforcer.ts

about: https://github.com/casbin/casbin-editor/issues/57
This implemet refers to https://casbin.org/docs/en/syntax-for-models#special-grammer

fix: fix `in` opertor

---

src/coreEnforcer.ts
src/util/util.ts
test/enforcer.test.ts
test/util.test.ts

This fixes https://github.com/casbin/node-casbin/issues/315.
I chose to go with a slightly more straightforward approach than what was done in https://github.com/casbin/casbin/pull/620; however, this meant modifying an existing util function instead of creating a new one.

fix(replaceeval): add third param to replaceEval and only replace eval() w/ matching ruleName

---

src/coreEnforcer.ts
src/enforcer.ts
test/rbac/defaultRoleManager.test.ts

this bug affects v5.5.0 to v5.11.4, it will reload role manager unexpected and make role matching fucntion lost.
resolve: #318 

fix: fix error overloading for role manager

---

examples/basic_keyget2_model.conf
examples/basic_keyget2_policy.csv
src/coreEnforcer.ts
test/enforcer.test.ts

Fix: https://github.com/casbin/node-casbin/issues/332
- added a case for result type string.
- please suggest changes if required.

fix: *matcher result should be boolean or number* for KeyGet2

---

src/enforcer.ts
test/rbacwDomainAPI.test.ts

Documentation indicates that there is existance of `getUsersForRoleInDomain` and
`getRolesForUserInDomain` api, but it does not yet exists. This commit implements these functions,
by aliasing them to existing rbac function that had already cater for domain apis, to increase and
improve dev experience.
Fix: https://github.com/casbin/node-casbin/issues/304

feat(rbac): implement `getUsersForRoleInDomain` & `getRolesForUserInDomain`

---

src/model/functionMap.ts
src/util/builtinOperators.ts
test/util.test.ts

support the keyMatch5 model function
Fix: https://github.com/casbin/node-casbin/issues/357

feat: #357 Support keyMatch5

---

examples/basic_keyget2_model.conf
examples/basic_keyget2_policy.csv
src/coreEnforcer.ts
src/enforcer.ts
src/model/functionMap.ts
src/util/builtinOperators.ts
test/rbacwDomainAPI.test.ts
test/util.test.ts

prepare for https://github.com/casbin/casbin-editor/issues/73
@hsluoyz @nodece plz review

chore: sync with main branch

---

src/coreEnforcer.ts
src/rbac/defaultRoleManager.ts
src/rbac/roleManager.ts
src/util/builtinOperators.ts
test/syncedEnforcer.test.ts

Based on @Zxilly 's work in: https://github.com/casbin/node-casbin/pull/303
Fixed the issue of `generateGFuncion` being async, therefore not working in syncedEnforcer.
I am not sure if the implementation is clear enough, but I created some tests which should cover the issue pretty well.

feat: add support for g() in SyncedEnforcer

---

src/internalEnforcer.ts
src/managementEnforcer.ts
src/syncedEnforcer.ts

- ref: https://github.com/casbin/casbin/issues/1092
- Moved all watcher calls from Internal methods to management enforcer

feat: add management api for watcherEx callbacks

---

examples/abac_attr_model.conf
examples/abac_attr_policy.csv
src/util/util.ts
test/enforcer.test.ts

- Fix #387
- updated the regex according to our needs

fix: escape assersion bug

---

package.json
yarn.lock

I'm not sure if this [issue](https://github.com/donmccurdy/expression-eval/issues/52) affects node-casbin but node-casbin is causing CI dependency check issues for me because of it. I hope you won't mind accepting my PR.

fix: update express-eval dependency to v5

---

examples/rbac_with_hierarchical_domains_model.conf
examples/rbac_with_hierarchical_domains_policy.csv
src/rbac/defaultRoleManager.ts
test/rbacHierarchicalDomain.test.ts

Work in progress. Initial idea from https://github.com/casbin/casbin/pull/1040
g2 defitions are in "reverse" order for reason. Other way around it would not work.
Discussion welcome.

feat(defaultrolemanager.ts): add hierarchical domain support for rbac

---

test/frontend.test.ts

Fix: #339
Fix line breaks CRLF in Windows caused the test faild.

fix: avoid the impact of line breaks CRLF in frontend.test.ts

---

src/enforcer.ts
src/index.ts
test/config/config.test.ts
test/model/model.test.ts
test/persist/fileSystem.test.ts

The `require` is unavailable in the ESM, so using the `import` instead.
Fix: https://github.com/casbin/node-casbin/issues/434

fix: using import() to load the fs

---

jest.config.js
package.json
src/persist/helper.ts
yarn.lock

For buffer: When the user uses the cabin on the browser, the `buffer` module is not found.
For csv-parse: The csv-parse@5 supports ESM and CJS versions.

fix: built-in buffer and upgrade csv-parse

---

src/util/util.ts
test/enforcer.test.ts

Fix: https://github.com/casbin/node-casbin/issues/438
Fixed unwanted replacement of r. in evals according to issue #438 (e.g. r.obj.owner.id wrongly becoming r_obj.owner_id instead of the correct r_obj.owner.id)

fix(./src/util/util.ts): fixed unwanted replacement of .r in evals

---

package.json
src/util/builtinOperators.ts
test/util.test.ts
yarn.lock

Fix https://github.com/casbin/node-casbin/issues/386
Replace: https://github.com/casbin/node-casbin/pull/393
The picomatch cannot be running in the browser, so use the mininmatch instead of the picomatch.

feat: replace picomatch with minimatch

---

src/util/util.ts

Fix #441 
This regex is generated by @openai chatGPT.

fix: escapeAssertion is compatible with safari

---

src/util/builtinOperators.ts
test/util.test.ts

Fixes: https://github.com/casbin/node-casbin/issues/457

fix: KeyMatch5 does not match the expected result

---

src/coreEnforcer.ts
src/model/model.ts

In a few places, it was still hardcoded to only look for the priority and effect of p, instead of using the ptype variable. Fixed so that it now has the same behaviour regardless of the order
fix #474

feat: ensure eft and priority are respected in p2, r2, etc

---

src/persist/fileSystem.ts
src/util/ip.ts

currently, the node-casbin is not compatible with Bun when running `bun build`
```
$ bun build src/index.ts --outdir ./build
28 | import { Buffer } from 'buffer';
^
error: No matching export in "node:buffer" for import "Buffer"
at /.../node_modules/casbin/lib/esm/util/ip.js:28:10
error: script "build" exited with code 1
```
there is a open issue about buffer import with Bun: https://github.com/oven-sh/bun/issues/8683
according to `feross/buffer` [docs](https://github.com/feross/buffer?tab=readme-ov-file#usage)
> To require this module explicitly, use require('buffer/') which tells the node.js module lookup algorithm (also used by browserify) to use the npm module named buffer instead of the node.js core module named buffer!
by adding trailing slash, this will use the `feross/buffer` …

feat: use `import { Buffer } from 'buffer/'` to be compatible with Bun

---

package.json
src/coreEnforcer.ts
src/util/util.ts
test/enforcer.test.ts
test/util.test.ts
yarn.lock

fix: https://github.com/casbin/node-casbin/issues/459

feat: switch dependency to our own package: @casbin/expression-eval 5.2.0

---

package.json
src/persist/fileAdapter.ts
src/persist/helper.ts
test/persist/helper.test.ts
yarn.lock

Part of: https://github.com/casbin/casbin-editor/issues/164
**Original Issue**
Limitations of CSV parser:
- The csv-parse library is mainly used for processing standard CSV format.
- Unable to handle complex policy expressions correctly
- Improper handling of commas and parentheses within quotation marks.
- Does not support nested expressions
**Improvement plan**
Custom parser:
```
const tokens: string[] = [];
let currentToken = '';
let inQuotes = false;
let bracketCount = 0;
```
- Can handle commas inside quotation marks
- Support nested parentheses
- Correctly handle escape characters

feat: add BracketAwareCsvParser to parse CSV file better

---

src/coreEnforcer.ts

Part of: https://github.com/casbin/casbin-editor/issues/193

feat: use empty array [] as reason for enforceEx()

---

src/coreEnforcer.ts
test/enforcer.test.ts

feat: implement `enableAcceptJsonRequest` API
